state = {
  data: [
    {
      id: "01",
      name: "Lomo Limpio",
      price: 38000,
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "../images/carne.jpg",
    },
    {
      id: "02",
      name: "Lomo Corriente",
      price: 33000,
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
    },
    {
      id: "03",
      name: "Chatas En Posta",
      price: 24000,
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
    },
    {
      id: "04",
      name: "CHURRASCO",
      price: 26000,
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
    },
    {
      id: "05",
      name: "PUNTA DE ANCA",
      price: 26000,
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
    },
    {
      id: "06",
      name: "CADERA EN POSTA",
      price: 20000,
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
    },
    {
      id: "07",
      name: "CADERA TAJADA",
      price: 20000,
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
    },
    {
      id: "08",
      name: "CENTRO DE PIERNA",
      price: 20000,
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
    },
    {
      id: "09",
      name: "BOTA",
      price: 19500,
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
    },
    {
      id: "10",
      name: "BOTA CON MUCHACHO",
      price: 20000,
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
    },
  ],
};
