const initialState = {
  cart: [],
  mylist: [],
  res: [
    {
      id: "01",
      name: "Lomo Limpio",
      price: "38.000",
      measues: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "02",
      name: "Lomo Corriente",
      price: "33.000",
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "03",
      name: "Chatas En Posta",
      price: "24.000",
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "04",
      name: "Churrasco",
      price: "26.000",
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "05",
      name: "Punta De Anca",
      price: "26.000",
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "06",
      name: "Cadera En Posta",
      price: "20.000",
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "07",
      name: "Cadera Tajada",
      price: "20.000",
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "08",
      name: "Centro De Pierna",
      price: "20.000",
      uniti: "kilogramo",
      amount: "500g",
      presentatio: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "09",
      name: "Bota",
      price: "19.500",
      uniti: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "10",
      name: "Bota Con Muchacho",
      price: "20.000",
      measues: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
  ],
  chicken: [
    {
      id: "56",
      name: "Pollo Entero",
      price: "7.600",
      measues: "kilogramo",
      amount: "x",
      presentation: "Entero",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "57",
      name: "Pechuga",
      price: "11.500",
      measues: "kilogramo",
      amount: "x",
      presentation: "Entera",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "58",
      name: "Filete De Pechuga",
      price: "16.000",
      measues: "kilogramo",
      amount: "x",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "59",
      name: "Pierna Pernil",
      price: "8.000",
      measues: "kilogramo",
      amount: "x",
      presentation: "Entero",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "60",
      name: "Pierna Pernil Deshuesado",
      price: "9.000",
      measues: "kilogramo",
      amount: "x",
      presentation: "Entero (Sin Hueso)",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "61",
      name: "Colombina De Pierna",
      price: "9.000",
      measues: "kilogramo",
      amount: "x",
      presentation: "Entero",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "62",
      name: "Muslos Enteros",
      price: "9.000",
      measues: "kilogramo",
      amount: "x",
      presentation: "Entero",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
  ],
  pig: [
    {
      id: "36",
      name: "Pernil De Cerdo",
      price: "15.000",
      measues: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "37",
      name: "Lomo De Cerdo",
      price: "18.000",
      measues: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "38",
      name: "Lomo Almendra",
      price: "20.000",
      measues: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "39",
      name: "Solomito",
      price: "22.000",
      measues: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "40",
      name: "Chuleta",
      price: "19.000",
      measues: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "41",
      name: "Brazo En Posta",
      price: "14.000",
      measues: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
    {
      id: "42",
      name: "Brazo Tajado",
      price: "14.000",
      measues: "kilogramo",
      amount: "500g",
      presentation: "Filete",
      img: "http://dummyimage.com/800x600.png/99118E/ffffff",
    },
  ],
};
export default initialState;
